In [6]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import seaborn as sns
import plotly.graph_objects as go
from matplotlib.sankey import Sankey
#from wordcloud import WordCloud,STOPWORDS
import warnings
warnings.filterwarnings("ignore")


In [12]:
#Reading excel file sheets
DonorDetails = pd.read_excel("OrganDonor_Consolidated.xlsx", "DonorDetails")
ReferralDetails=pd.read_excel("OrganDonor_Consolidated.xlsx", "ReferralDetails")
Outcomes=pd.read_excel("OrganDonor_Consolidated.xlsx", "Outcomes")
OPO_HospDetails=pd.read_excel("OrganDonor_Consolidated.xlsx", "OPO_HospDetails")
Yearly_Outcomes=pd.read_excel("OrganDonor_Consolidated.xlsx", "Yearly_Outcomes")


In [18]:
ReferralDetails.nunique()

PatientID               133101
Approached Relatives         2
Authorized By Family         2
Cross_Clamped                2
transplanted                 2
Tissue_Referral              2
Eye_Referral                 2
time_referred           132791
time_approached          21685
time_authorized          19694
time_procured             9531
Referral_DayofWeek           7
Referral_Year                7
Procured_Year                9
dtype: int64

**1. Using numpy functions, multiply the following arrays using matrix multiplication.
 a=np.arange(4).reshape(2,2)
 b=np.arange(6).reshape(3,2)**
 
 

In [36]:
a=np.arange(4).reshape(2,2)
b=np.arange(6).reshape(3,2)
print(a)

#Transposing array b:
print(f'Original Array:\n{b}')
b_transpose=b.transpose()
print(f'Transposed Array:\n{b_transpose}')

#Matrix Multiplication
matrix=np.matmul(a,b_transpose)

print(f'Final Reult:\n{matrix}')

[[0 1]
 [2 3]]
Original Array:
[[0 1]
 [2 3]
 [4 5]]
Transposed Array:
[[0 2 4]
 [1 3 5]]
Final Reult:
[[ 1  3  5]
 [ 3 13 23]]
